rjo6615/DnD

server/__tests__/characters.test.js, server/routes.js
=> Revert "Protect character creation with auth"

server/server.js
=> Revert "Use explicit env config path for server"

client/src/components/Zombies/attributes/Feats.js
=> Revert "Update Feat endpoints to new characters API"

server/routes/auth.js, server/server.js
=> Revert "Specify realmtracker cookie domain"

client/src/components/Zombies/pages/Zombies.js, client/src/components/Zombies/pages/ZombiesDM.js
=> Revert "Fix Zombies campaign route prefixes"

server/routes/auth.js, server/server.js
=> Revert "Align cookie settings for cross-origin requests"

client/src/hooks/useUser.js, client/src/hooks/useUser.test.js, server/routes/auth.js, server/routes/users.js
=> Revert "Handle DM roles in auth and user hook"

client/src/App.scss, client/src/components/Footer/Footer.js, client/src/components/Login/Login.css, client/src/components/Navbar/Navbar.js, client/src/components/Zombies/attributes/HealthDefense.js, client/src/components/Zombies/attributes/PlayerTurnActions.js, client/src/components/Zombies/pages/Zombies.js, client/src/components/Zombies/pages/ZombiesCharacterSelect.js, client/src/components/Zombies/pages/ZombiesCharacterSheet.js, client/src/components/Zombies/pages/ZombiesDM.js
=> Revert "Set white background defaults"

client/src/App.scss, client/src/components/Zombies/pages/Zombies.js, client/src/components/Zombies/pages/ZombiesCharacterSheet.js
=> Revert "Use login background image for zombies pages"

client/src/components/Zombies/attributes/Weapons.js
=> Revert "Refactor weapons modal layout"

client/src/App.scss, client/src/components/Zombies/attributes/Skills.js
=> Revert "Enhance skill checkbox styling"

client/src/components/Zombies/attributes/HealthDefense.js, client/src/components/Zombies/attributes/Skills.js, client/src/utils/proficiencyBonus.js
=> Revert "Add proficiency bonus helper and show bonus in health stats"

client/src/components/Zombies/attributes/Skills.js, client/src/components/Zombies/skillSchema.js
=> Revert "Add skill descriptions with view modal"

client/src/components/Zombies/attributes/SpellSlots.js
=> Revert "Refactor spell slot container structure"

client/src/components/Zombies/attributes/SpellSlots.js
=> Revert "Refactor spell slot layout"

client/src/App.scss
=> Revert "Add d4 die styles and animation"

client/src/App.scss
=> Revert "refactor bonus triangle styling with clip-path"

client/src/components/Zombies/attributes/SpellSlots.js, client/src/components/Zombies/attributes/SpellSlots.test.js, client/src/components/Zombies/pages/ZombiesCharacterSheet.js
=> Revert "Add dynamic action and bonus spell slots"

client/package.json, client/src/components/Zombies/pages/ZombiesDM.js
=> Revert "feat: add AI weapon generation to DM page"

client/src/App.scss, client/src/components/Zombies/attributes/SpellSlots.js, client/src/components/Zombies/attributes/SpellSlots.test.js, client/src/components/Zombies/pages/ZombiesCharacterSheet.test.js
=> Revert "Revert "Switch bonus action marker to circle""

README.md, client/package-lock.json, client/package.json, client/src/__mocks__/openai.js, client/src/__mocks__/openai/helpers/zod.js, client/src/components/Items/ItemList.js, client/src/components/Zombies/attributes/Items.js, client/src/components/Zombies/attributes/PlayerTurnActions.js, client/src/components/Zombies/attributes/PlayerTurnActions.test.js, client/src/components/Zombies/attributes/Skills.js, client/src/components/Zombies/attributes/Skills.test.js, client/src/components/Zombies/attributes/SpellSelector.js, client/src/components/Zombies/attributes/Stats.js, client/src/components/Zombies/attributes/Stats.test.js, client/src/components/Zombies/pages/ZombiesCharacterSheet.js, client/src/components/Zombies/pages/ZombiesCharacterSheet.test.js, client/src/components/Zombies/pages/ZombiesDM.js, client/src/components/Zombies/pages/ZombiesDM.test.js, client/src/components/Zombies/skillSchema.js, server/__tests__/ai.test.js, server/__tests__/equipment.test.js, server/__tests__/items.test.js, server/data/items.js, server/package-lock.json, server/package.json, server/routes/ai.js, server/routes/equipment.js, server/routes/index.js, server/routes/items.js, types/item.d.ts
=> Revert "Revert "Ai fixes""

server/__tests__/spells.test.js, server/routes/spells.js
=> Revert "Include damage type in spell parsing"

client/src/App.scss, client/src/components/Zombies/attributes/PlayerTurnActions.js, server/__tests__/spells.test.js, server/routes/spells.js, types/spell.d.ts
=> Revert "Parse and surface spell damage types"

client/src/components/Zombies/attributes/PlayerTurnActions.js, client/src/components/Zombies/attributes/PlayerTurnActions.test.js, client/src/components/Zombies/pages/ZombiesCharacterSheet.js, client/src/components/Zombies/pages/ZombiesCharacterSheet.test.js
=> Revert "Display damage breakdown for spell attacks"

client/src/App.scss, client/src/components/Navbar/Navbar.js, client/src/components/Zombies/attributes/Help.js
=> Revert "Align help logout button with navbar styling"

client/src/components/Zombies/attributes/Features.js, client/src/components/Zombies/attributes/PlayerTurnActions.js, client/src/components/Zombies/attributes/PlayerTurnActions.test.js, client/src/components/Zombies/pages/ZombiesCharacterSelect.js, client/src/components/Zombies/pages/ZombiesCharacterSheet.js, server/data/races.js
=> Dragonborn

client/src/components/Zombies/pages/ZombiesDM.js, server/__tests__/campaigns.test.js, server/routes/campaigns.js, server/utils/campaignMaps.js
=> Revert "Preserve token size metadata in map token updates"
